In [207]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [121]:
df_base = pd.read_csv('hay_fever.csv', low_memory = False)

In [124]:
df_base.head()

PMID  OWN                STAT          LR  \
0  33191381  NLM      In-Data-Review  20201116.0   
1  33171477  NLM           Publisher  20201110.0   
2  33160969  NLM           Publisher  20201108.0   
3  33141493  NLM           Publisher  20201103.0   
4  33134525  NLM  PubMed-not-MEDLINE  20201103.0   

                                           IS   VI   IP           DP       PG  \
0       0021-4884 (Print) 0021-4884 (Linking)   69    9         2020  928-929   
1  1423-0097 (Electronic) 1018-2438 (Linking)  NaN  NaN  2020 Nov 10     1-10   
2  1097-6825 (Electronic) 0091-6749 (Linking)  NaN  NaN   2020 Nov 5      NaN   
3  1365-2222 (Electronic) 0954-7894 (Linking)  NaN  NaN   2020 Nov 3      NaN   
4       2378-8038 (Print) 2378-8038 (Linking)    5    5     2020 Oct  807-808   

                                                 LID  ...  ORI SPIN  UIN   CP  \
0                      10.15036/arerugi.69.928 [doi]  ...  NaN  NaN  NaN  NaN   
1                            10.1159/000510942 [doi]  ...  NaN  NaN  NaN  NaN   
2  S0091-6749(20)31561-X [pii] 10.1016/j.jaci.202...  ...  NaN  NaN  NaN  NaN   
3                            10.1111/cea.13775 [doi]  ...  NaN  NaN  NaN  NaN   
4                             10.1002/lio2.459 [doi]  ...  NaN  NaN  NaN  NaN   

   RF  RPF  RPI  RIN   GS  Year  
0 NaN  NaN  NaN  NaN  NaN  2020  
1 NaN  NaN  NaN  NaN  NaN  2020  
2 NaN  NaN  NaN  NaN  NaN  2020  
3 NaN  NaN  NaN  NaN  NaN  2020  
4 NaN  NaN  NaN  NaN  NaN  2020  

[5 rows x 78 columns]

In [125]:
df_base.shape

(15766, 78)

In [127]:
pd.options.display.max_rows = 4000

df_base.isna().sum()

PMID        0
OWN        19
STAT        0
LR         19
IS        196
VI        295
IP       1637
DP          0
PG         89
LID     12116
LA          0
PT          0
PL          0
TA         19
JT         19
JID        19
SB        423
OTO     13185
OT      13185
EDAT        0
MHDA        0
CRDT       19
PHST       19
AID      5996
PST        19
SO         19
TI          6
AB       5599
CI      14256
FAU       250
AU        250
AD       6346
DEP     12981
AUID    15507
PMC     14358
COIS    15634
DCOM      264
MH        490
GR      14847
TT      13022
CN      15513
RN       4823
DA      15747
CTDT    15754
PB      15747
BTI     15747
CDAT    15747
IR      15695
FIR     15695
SI      15616
EFR     15762
UOF     15758
PMCR    15759
EIN     15638
MID     15600
CIN     15312
CON     15509
OAB     15759
OABL    15759
PS      15742
FPS     15742
IRAD    15763
CTI     15762
OID     15006
GN      15754
ISBN    15762
FED     15763
ED      15763
ORI     15765
SPIN    15764
UIN     15758
CP    

Columns of Interest

| Column | Field |
|--------|-------|
|'AB'|Abstract|
|'AD'|Affiliation|
|'AID'|Article Identifier|
|'AU'|Author|
|'CI'|Copyright Information|
|'CIN'|Comment In|
|'DP'|Date of Publication|
|'FAU'|Full Author|
|'FIR'|Full Investigator Name|
|'IP'|Issue|
|'IR'|Investigator Name|
|'IS'|ISSN|
|'JID'|NLM Unique ID|
|'JT'|Journal Title|
|'LA'|Language|
|'LID'|Location Identifier|
|'LR'|Date Last Revised|
|'MH'|MeSH Terms|
|'OT'|Other Term|
|'OWN'|Owner|
|'PG'|Pagination|
|'PHST'|Publication History Status|
|'PL'|Place of Publication|
|'PMID'|PubMed Unique Identifier|
|'PST'|Publication Status|
|'PT'|Publication Type|
|'RF'|Number of References|
|'SB'|Subset|
|'SO'|Source|
|'STAT'|Status|
|'TA'|Journal Title Abbreviation|
|'TI'|Title|
|'VI'|Volume|
|'Year'|Year|

Removed Columns


| Column | Field |
|--------|-------|
|'OTO'|Other Term Owner|
|'RN'|Registry Number|
|'PMCR'|PubMed Central Release|
|'EIN'|Erratum in|
|'MID'|Manuscript Identifier|
|'EDAT'|Entrez Date|
|'MHDA'|MeSH Date|
|'CRDT'|Create Date|
|'COIS'|Conflict of Interest Statement|
|'AUID'|Author Identifier|
|'GR'|Grant Number|
|'DCOM'|Date Completed|
|'PMC'|Pubmed Central Identifier|
|'DEP'|Date of Electronic Publication|
|'CI'|Copyright Information|
|'LID'|Location Identifier|
|'EFR'|Erratum For|
|'SI'|Secondary Source ID|
|'CON'|Comment On|
|'CN'|Corporate Author|
|'TT'|Transliterated Title|
|'RIN'|Retraction In|
|'ECI'|Expression of Concern||'OID'|Other ID|
|'DA'|Date Created|
|'ISBN'|ISBN|
|'PB'|
|'BTI'|Book Title|
|'FPS'|Full Personal Name as Subject|
|'CDAT'|
|'CP'|
|'FED'|Full Editor Name|
|'ED'|Editor Name|
|'RPF'|Republished From|
|'PS'|Personal Name as Subject|
|'GN'|General Note|
|'DRDT'|
|'CTDT'|
|'RPI'|Republished In|
|'GS'|Gene Symbol|


In [128]:
cols = ['AB', 'AD', 'AID', 'AU', 'CI', 'CIN', 'DP', 'FAU', 'FIR', 'IP', 'IR', 'IS', 'JID', 'JT', 'LA', 'LID', 'LR', 'MH', 'OT', 'OWN', 'PG', 'PHST', 'PL', 'PMID', 'PST', 'PT', 'RF', 'SB', 'SO', 'STAT', 'TA', 'TI', 'VI', 'Year']
df = df_base[cols]


# FSM

Our FSM will consist of finding the highest referenced document in our search, and then using content-based recommendation to find 5 other documents that are similar to it in regards to the keyterms of the first document

In [130]:
df['RF'].fillna(0, inplace = True)

In [131]:
df['RF'].astype(int)

0        0
1        0
2        0
3        0
4        0
        ..
15761    0
15762    0
15763    0
15764    0
15765    0
Name: RF, Length: 15766, dtype: int32

In [156]:
df[~df['MH'].isna()].shape

(15276, 35)

In [154]:
df[~df['MH'].isna()]['MH'][5].strip('][').split('\'')

['',
 'Humans',
 ', ',
 'Japan',
 ', ',
 'Macrophages',
 ', ',
 '*Rhinitis, Allergic',
 ', ',
 '*Rhinitis, Allergic, Seasonal',
 ', ',
 'Th1 Cells',
 ', ',
 'Th2 Cells',
 '']

In [235]:
df_terms = df[~df['MH'].isna() | ~df['OT'].isna()].reset_index(drop = True)
df_terms.fillna({'MH': '', 'OT': ''}, inplace = True)

In [236]:
df_terms.head()

AB  \
0                                                NaN   
1  BACKGROUND: Epithelial gene expression in alle...   
2  BACKGROUND: Allergen-specific immunotherapy (A...   
3  BACKGROUND: Local tissue eosinophilia and Th2-...   
4                                                NaN   

                                                  AD  \
0                                                NaN   
1  ['Department of Otolaryngology-Head and Neck S...   
2  ['Immunomodulation and Tolerance Group, Allerg...   
3  ['Allergy and Clinical Immunology, National He...   
4  ['Department of Otorhinolaryngology Careggi Un...   

                                                 AID  \
0                  ['10.15036/arerugi.69.928 [doi]']   
1     ['000510942 [pii]', '10.1159/000510942 [doi]']   
2  ['S0091-6749(20)31561-X [pii]', '10.1016/j.jac...   
3                        ['10.1111/cea.13775 [doi]']   
4        ['10.1002/lio2.459 [doi]', 'LIO2459 [pii]']   

                                                  AU  \
0                                                NaN   
1  ['Wang M', 'She W', 'Yang J', 'Wang X', 'Zhang...   
2  ['Sharif H', 'Acharya S', 'Dhondalay GKR', 'Va...   
3  ['Orban N', 'Jacobson MR', 'Nouri-Aria KT', 'D...   
4  ['Gallo O', 'Bruno C', 'Orlando P', 'Locatello...   

                                                  CI  CIN           DP  \
0                                                NaN  NaN         2020   
1                  ['(c) 2020 S. Karger AG, Basel.']  NaN  2020 Nov 10   
2  ['Copyright (c) 2020. Published by Elsevier In...  NaN   2020 Nov 5   
3  ['This article is protected by copyright. All ...  NaN   2020 Nov 3   
4                                                NaN  NaN     2020 Oct   

                                                 FAU  FIR   IP  ...  \
0                                                NaN  NaN    9  ...   
1  ['Wang, Min', 'She, Wenyu', 'Yang, Jun', 'Wang...  NaN  NaN  ...   
2  ['Sharif, Hanisah', 'Acharya, Swati', 'Dhondal...  NaN  NaN  ...   
3  ['Orban, Nara', 'Jacobson, Mikila R', 'Nouri-A...  NaN  NaN  ...   
4  ['Gallo, Oreste', 'Bruno, Chiara', 'Orlando, P...  NaN    5  ...   

                    PT   RF      SB  \
0  ['Journal Article']  0.0      IM   
1  ['Journal Article']  0.0      IM   
2  ['Journal Article']  0.0  AIM IM   
3  ['Journal Article']  0.0      IM   
4  ['Journal Article']  0.0     NaN   

                                                  SO                STAT  \
0  Arerugi. 2020;69(9):928-929. doi: 10.15036/are...      In-Data-Review   
1  Int Arch Allergy Immunol. 2020 Nov 10:1-10. do...           Publisher   
2  J Allergy Clin Immunol. 2020 Nov 5. pii: S0091...           Publisher   
3  Clin Exp Allergy. 2020 Nov 3. doi: 10.1111/cea...           Publisher   
4  Laryngoscope Investig Otolaryngol. 2020 Sep 11...  PubMed-not-MEDLINE   

                                  TA  \
0                            Arerugi   
1           Int Arch Allergy Immunol   
2             J Allergy Clin Immunol   
3                   Clin Exp Allergy   
4  Laryngoscope Investig Otolaryngol   

                                                  TI   VI  Year terms  
0                                                NaN   69  2020   NaN  
1  Gene Expression Analysis by Real-Time PCR in N...  NaN  2020   NaN  
2  Grass pollen immunotherapy alters chromatin la...  NaN  2020   NaN  
3  Repetitive nasal allergen challenge in allergi...  NaN  2020   NaN  
4  The impact of lockdown on allergic rhinitis: W...    5  2020   NaN  

[5 rows x 35 columns]

In [261]:
def clean_terms(x):
    punctuation = '*&'
    s = x.strip('][').split('\'')
    s = [w for w in s if w != ', ']
    s = [w for w in s if w != '']
    s = [w.lower() for w in s]
    s = [w.translate(w.maketrans('', '', punctuation)) for w in s]
    return ' '.join(s)

In [264]:
df_terms['mh_t'] = df_terms['MH'].apply(clean_terms)
df_terms['ot_t'] = df_terms['OT'].apply(clean_terms)
df_terms['terms'] = df_terms['mh_t'] + ' ' + df_terms['ot_t']

In [283]:
df_terms['terms'][15542]

'ambrosia anaphylaxis antigens biometry hypersensitivity immune system diseases rhinitis, allergic, seasonal/epidemiology/statistics & numerical data anaphylaxis and allergy hay fever/epidemiology and statistics'

In [200]:
df_terms = df_terms.sort_values(by = 'RF', ascending = False).reset_index(drop = True)

In [201]:
best = df_terms.head(1)

In [202]:
best

AB                                                 AD  \
0  NaN  ['University Hospital and INSERM, Hopital Arna...   

                                                 AID  \
0  ['ALL1620 [pii]', '10.1111/j.1398-9995.2007.01...   

                                                  AU   CI  CIN        DP  \
0  ['Bousquet J', 'Khaltaev N', 'Cruz AA', 'Denbu...  NaN  NaN  2008 Apr   

                                                 FAU  FIR   IP  ...  \
0  ['Bousquet, J', 'Khaltaev, N', 'Cruz, A A', 'D...  NaN  NaN  ...   

                                                  PT      RF  SB  \
0  ['Journal Article', 'Practice Guideline', "Res...  2241.0  IM   

                                                  SO     STAT       TA  \
0  Allergy. 2008 Apr;63 Suppl 86:8-160. doi: 10.1...  MEDLINE  Allergy   

                                                  TI           VI  Year  \
0  Allergic Rhinitis and its Impact on Asthma (AR...  63 Suppl 86  2008   

                                               terms  
0  Adolescent Asthma/epidemiology/*etiology/thera...  

[1 rows x 35 columns]

In [203]:
cv = CountVectorizer()
X = cv.fit_transform(df_terms['terms'])
X = pd.DataFrame.sparse.from_spmatrix(X)
X.columns = sorted(cv.vocabulary_)
X = X.to_numpy()

numerators = np.array([X[0].dot(i) for i in X[1:]])
denominators = np.array([np.sqrt(sum(X[0]**2)) *\
                         np.sqrt(sum(i**2)) for i in X[1:]])

results = numerators / denominators

In [219]:
print(results)

[0.24366633 0.60328193 0.20286368 ... 0.08084521 0.2655274  0.28924061]


Results will be found by matching the 5 highest cosine similarities, and the matching them to the correct index; will finish after dinner

In [268]:
ind = np.argpartition(results, -4)[-4:]

In [269]:
ind

array([13958, 15035,   191,   165], dtype=int64)

In [271]:
results[ind]

array([0.75300747, 0.75740971, 0.76015205, 0.7970534 ])

In [280]:
list(df_terms.iloc[ind]['TI'])

['Allergic shiners. Dark circles under the eyes in children.',
 '[Treatment of allergic patients with plimasin].',
 'Cat and dog ownership during/after the first year of life and risk for sensitization and reported allergy symptoms at age 13.',
 'Residential green space and seasonal distress in a cohort of tree pollen allergy patients.']